stages:
    - code-quality

lint:
    stage: code-quality
    tags:
        - npm
    script:
        - npm install --legacy-peer-deps
        - npm run lint
    cache:
        key: $CI_COMMIT_REF_SLUG
        paths:
            - package-lock.json
            - node_modules
