import type { Metadata } from "next";

import "./globals.css";

import Footer from "@/components/Footer/Footer";
import HeaderDefault from "@/components/Header/HeaderDefault";
import HeaderLoggedIn from "@/components/Header/HeaderLoggedIn";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                {<HeaderDefault />}
                {children}
                {<Footer />}
            </body>
        </html>
    );
}
