import type { Metadata } from "next";
import "./globals.css";
import HeaderDefault from "@/components/custom/Header/HeaderDefault";
import HeaderLoggedIn from "@/components/custom/Header/HeaderLoggedIn";
import Footer from "@/components/custom/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {<HeaderDefault />}
        {children}
        {<Footer />}
      </body>
    </html>
  );
}
